name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to the project directory
          cd inventorynestreactprod

          # Pull the latest changes
          git pull origin master
          git status

          # Install dependencies
          npm install --only=prod

          # Build the React app
          npm run build

          # Stop the existing PM2 process if it exists
          pm2 delete inventorynestreactprod || true

          # Start the server using PM2 and serve
          pm2 start serve --name inventorynestreactprod -p 3000 -s build -l pm2.log --watch --spa

          # Ensure PM2 restarts after a reboot
          pm2 save
          pm2 startup
