name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd inventorynestreactprod
          git pull origin master
          git status

          # Install dependencies
          npm install --only=prod

          # Build the React app
          npm run build

          # Install 'serve' if not already installed (uncomment the next line if needed)
          npm install -g serve

          # Stop the existing PM2 process if it exists
          pm2 stop inventorynestreactprod || true

          # Start the server using PM2 and serve
          pm2 start "serve -s build" --name inventorynestreactprod -p 3000
          