name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Set the PATH to include the location of Node.js and global npm packages
          export PATH="/home/ubuntu/.nvm/versions/node/v18.17.1/bin:$PATH"

          # Change to the project directory
          cd inventorynestreactprod
          git pull origin master
          git status

          # Install dependencies
          npm install --only=prod

          # Build the React app
          npm run build

          # Stop the existing PM2 process if it exists
          pm2 stop inventorynestreactprod || true

          # Start the server using PM2 and the full path to 'serve'
          pm2 reload inventorynestreactprod || pm2 start "/home/ubuntu/.nvm/versions/node/v18.17.1/bin/serve -s build" --name inventorynestreactprod --watch
