name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
        

          # Change to the project directory
          cd inventorynestreactprod
          git pull origin master
          git status

          # Install dependencies (including dev dependencies)
          npm install

          # Stop the existing PM2 process if it exists
          pm2 stop inventorynestreactprod || true

          # Start the server using PM2 and npm run dev
          pm2 reload inventorynestreactprod || pm2 start npm run dev --name inventorynestreactprod --watch

